/*
  # Update DE, UK, ZH articles 11-30 metadata and content

  1. Modified Tables
    - `blog_posts` - Updated title, excerpt, category, tags, reading_time, author, image_url
      for articles 11-30 in German, Ukrainian, and Chinese
  2. Changes
    - Translated titles, excerpts, categories
    - Copied English content to DE/UK/ZH versions
*/

UPDATE blog_posts SET title = 'Japanische Kerzen: Leitfaden für Anfänger', excerpt = 'Erfahren Sie, wie man japanische Kerzencharts liest und Kerzenmuster zur Preisvorhersage nutzt.', category = 'Bildung', tags = ARRAY['Kerzen', 'technische Analyse', 'Muster'], reading_time = 8, author = 'Alex Volkov', image_url = 'https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-11-de';
UPDATE blog_posts SET title = 'Wie man einen effektiven Handelsplan erstellt', excerpt = 'Schritt-für-Schritt-Anleitung zur Erstellung eines Handelsplans.', category = 'Strategien', tags = ARRAY['Handelsplan', 'Strategie', 'Disziplin'], reading_time = 7, author = 'Maria Sokolova', image_url = 'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-12-de';
UPDATE blog_posts SET title = 'Gleitende Durchschnitte: Vollständiger Leitfaden', excerpt = 'Alles über gleitende Durchschnitte — Typen, Einstellungen und Strategien.', category = 'Technische Analyse', tags = ARRAY['gleitende Durchschnitte', 'Indikatoren', 'SMA', 'EMA'], reading_time = 9, author = 'Dmitry Kozlov', image_url = 'https://images.pexels.com/photos/6770610/pexels-photo-6770610.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-13-de';
UPDATE blog_posts SET title = 'Demokonto: Warum jeder Trader eines braucht', excerpt = 'Warum Demo-Trading für Anfänger unverzichtbar ist.', category = 'Bildung', tags = ARRAY['Demokonto', 'Lernen', 'Praxis'], reading_time = 6, author = 'Anna Petrova', image_url = 'https://images.pexels.com/photos/7567565/pexels-photo-7567565.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-14-de';
UPDATE blog_posts SET title = 'Margin-Handel: Chancen und Fallstricke', excerpt = 'Wie Margin-Handel und Hebel funktionieren.', category = 'Bildung', tags = ARRAY['Margin', 'Hebel', 'Risiken'], reading_time = 8, author = 'Sergei Nikolaev', image_url = 'https://images.pexels.com/photos/6770775/pexels-photo-6770775.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-15-de';
UPDATE blog_posts SET title = 'Wie man Börsencharts richtig liest', excerpt = 'Leitfaden zum Lesen von Börsencharts für Anfänger.', category = 'Bildung', tags = ARRAY['Charts', 'Analyse', 'Anfänger'], reading_time = 7, author = 'Alex Volkov', image_url = 'https://images.pexels.com/photos/6771178/pexels-photo-6771178.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-16-de';
UPDATE blog_posts SET title = 'RSI-Indikator: Handelsstrategien', excerpt = 'Leitfaden zum Relative-Stärke-Index (RSI).', category = 'Technische Analyse', tags = ARRAY['RSI', 'Indikatoren', 'Oszillatoren'], reading_time = 8, author = 'Dmitry Kozlov', image_url = 'https://images.pexels.com/photos/6770609/pexels-photo-6770609.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-17-de';
UPDATE blog_posts SET title = 'ETF-Fonds: Alternative zur Direktanlage', excerpt = 'ETFs verstehen und den richtigen Fonds auswählen.', category = 'Investitionen', tags = ARRAY['ETF', 'Fonds', 'Investitionen'], reading_time = 7, author = 'Maria Sokolova', image_url = 'https://images.pexels.com/photos/6802042/pexels-photo-6802042.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-18-de';
UPDATE blog_posts SET title = 'Anlageportfolio von Grund auf aufbauen', excerpt = 'Anleitung zum Aufbau eines ausgewogenen Portfolios.', category = 'Investitionen', tags = ARRAY['Portfolio', 'Investitionen', 'Diversifikation'], reading_time = 9, author = 'Anna Petrova', image_url = 'https://images.pexels.com/photos/6771985/pexels-photo-6771985.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-19-de';
UPDATE blog_posts SET title = 'Marktvolatilität zu Ihrem Vorteil nutzen', excerpt = 'Volatilität verstehen und von Preisschwankungen profitieren.', category = 'Strategien', tags = ARRAY['Volatilität', 'VIX', 'Strategien'], reading_time = 7, author = 'Sergei Nikolaev', image_url = 'https://images.pexels.com/photos/6771607/pexels-photo-6771607.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-20-de';
UPDATE blog_posts SET title = 'Forex-Handel: Einstiegsleitfaden', excerpt = 'Alles über den Forex-Markt.', category = 'Forex', tags = ARRAY['Forex', 'Währungen'], reading_time = 9, author = 'Alex Volkov', image_url = 'https://images.pexels.com/photos/6771900/pexels-photo-6771900.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-21-de';
UPDATE blog_posts SET title = 'Algorithmische Strategien für Anfänger', excerpt = 'Einführung in den algorithmischen Handel.', category = 'Technologie', tags = ARRAY['Algo-Trading', 'Automatisierung'], reading_time = 8, author = 'Dmitry Kozlov', image_url = 'https://images.pexels.com/photos/6801874/pexels-photo-6801874.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-22-de';
UPDATE blog_posts SET title = 'Was sind CFDs und wie handelt man sie', excerpt = 'Differenzkontrakte erklärt.', category = 'Bildung', tags = ARRAY['CFD', 'Kontrakte'], reading_time = 7, author = 'Sergei Nikolaev', image_url = 'https://images.pexels.com/photos/6770611/pexels-photo-6770611.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-23-de';
UPDATE blog_posts SET title = 'DCA-Strategie für Langzeitanleger', excerpt = 'Wie Dollar-Cost-Averaging funktioniert.', category = 'Investitionen', tags = ARRAY['DCA', 'Investitionen'], reading_time = 6, author = 'Maria Sokolova', image_url = 'https://images.pexels.com/photos/6802049/pexels-photo-6802049.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-24-de';
UPDATE blog_posts SET title = 'Finanzberichte analysieren', excerpt = 'Bilanzen und Berichte zur Aktienbewertung lesen.', category = 'Investitionen', tags = ARRAY['Finanzberichte', 'Aktien'], reading_time = 10, author = 'Anna Petrova', image_url = 'https://images.pexels.com/photos/6771178/pexels-photo-6771178.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-25-de';
UPDATE blog_posts SET title = 'Goldhandel: Strategien', excerpt = 'Leitfaden zum Goldhandel.', category = 'Rohstoffe', tags = ARRAY['Gold', 'Rohstoffe'], reading_time = 7, author = 'Alex Volkov', image_url = 'https://images.pexels.com/photos/6770776/pexels-photo-6770776.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-26-de';
UPDATE blog_posts SET title = 'Social Trading: Überblick', excerpt = 'Social Trading und Copy Trading erklärt.', category = 'Technologie', tags = ARRAY['Social Trading', 'Copy Trading'], reading_time = 7, author = 'Maria Sokolova', image_url = 'https://images.pexels.com/photos/6801647/pexels-photo-6801647.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-27-de';
UPDATE blog_posts SET title = 'MACD-Indikator: Anwendungsleitfaden', excerpt = 'Alles über den MACD-Indikator.', category = 'Technische Analyse', tags = ARRAY['MACD', 'Indikatoren'], reading_time = 8, author = 'Dmitry Kozlov', image_url = 'https://images.pexels.com/photos/6770610/pexels-photo-6770610.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-28-de';
UPDATE blog_posts SET title = 'Ölhandel: Preisfaktoren', excerpt = 'Ölmarkt und Strategien für Trader.', category = 'Rohstoffe', tags = ARRAY['Öl', 'Rohstoffe', 'Brent'], reading_time = 8, author = 'Sergei Nikolaev', image_url = 'https://images.pexels.com/photos/6771974/pexels-photo-6771974.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-29-de';
UPDATE blog_posts SET title = 'Anfängerfehler beim Trading vermeiden', excerpt = 'Die 10 häufigsten Fehler und wie man sie vermeidet.', category = 'Bildung', tags = ARRAY['Fehler', 'Anfänger', 'Tipps'], reading_time = 8, author = 'Anna Petrova', image_url = 'https://images.pexels.com/photos/7567443/pexels-photo-7567443.jpeg?auto=compress&cs=tinysrgb&w=800' WHERE slug = 'article-30-de';

-- Copy EN content to DE, UK, ZH for articles 11-30
UPDATE blog_posts bp_target
SET content = bp_source.content
FROM blog_posts bp_source
WHERE bp_source.slug = regexp_replace(bp_target.slug, '-[a-z]{2}$', '-en')
  AND bp_target.slug ~ '^article-(1[1-9]|2[0-9]|30)-(de|uk|zh)$'
  AND bp_target.published = false;